"""
DeepSeek-R1 8B optimized prompt templates
Reasoning-focused prompts for code and security analysis
"""

from .analyst import (
    ANALYST_SYSTEM_PROMPT,
    ANALYST_INTERPRET_PROMPT,
    ANALYST_CORRELATION_PROMPT,
    ANALYST_FALSE_POSITIVE_PROMPT,
)

from .planner import (
    PLANNER_SYSTEM_PROMPT,
    PLANNER_DECISION_PROMPT,
    PLANNER_ANALYSIS_PROMPT,
)

from .reporter import (
    REPORTER_SYSTEM_PROMPT,
    REPORTER_EXECUTIVE_SUMMARY_PROMPT,
    REPORTER_TECHNICAL_FINDINGS_PROMPT,
    REPORTER_REMEDIATION_PROMPT,
    REPORTER_AI_TRACE_PROMPT,
)

__all__ = [
    # Analyst
    "ANALYST_SYSTEM_PROMPT",
    "ANALYST_INTERPRET_PROMPT",
    "ANALYST_CORRELATION_PROMPT",
    "ANALYST_FALSE_POSITIVE_PROMPT",
    # Planner
    "PLANNER_SYSTEM_PROMPT",
    "PLANNER_DECISION_PROMPT",
    "PLANNER_ANALYSIS_PROMPT",
    # Reporter
    "REPORTER_SYSTEM_PROMPT",
    "REPORTER_EXECUTIVE_SUMMARY_PROMPT",
    "REPORTER_TECHNICAL_FINDINGS_PROMPT",
    "REPORTER_REMEDIATION_PROMPT",
    "REPORTER_AI_TRACE_PROMPT",
]
